### ISSUE TITLE
Create release

### ISSUE THREAD

**Issue by icemac** [zopefoundation/zope.processlifetime#5]
Please create a release or add `icemac` to the persons with PyPI rights so I can do it on my own.

**Comment by jamadden** [comment]
Both done!

**Comment by mgedmin** [comment]
I think I'm a 'maintainer' but not an 'owner' because I see myself in the Maintainers list on PyPI, but I have no 'Manage project' button for this project.

**Comment by icemac** [comment]
@jamadden Thanks a lot!

**Comment by jamadden** [comment]
@mgedmin levelled up!
